packages:
  - "packages/*"
  - "packages/plugins/*"
  - "apps/*"
  - "apps/cloudflare/frontend"
  - "apps/server/client"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: set this to true or false
  workerd: true

catalog:
  "@stylexjs/stylex": 0.19.0
  "@stylexjs/unplugin": 0.19.0
  effect: 4.0.0-rc.112
  "@effect/opentelemetry": 4.0.0-rc.112
  "@effect/platform-browser": 4.0.0-rc.112
  "@effect/platform-bun": 4.0.0-rc.112
  "@effect/platform-node": 4.0.0-rc.112
  "@effect/platform-node-shared": 4.0.0-rc.112
  "@effect/vitest": 4.0.0-rc.112
