packages:
  - "packages/*"
  - "packages/plugins/*"
  - "apps/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: set this to true or false
  workerd: true

catalog:
  effect: 4.0.0-beta.101
  "@effect/opentelemetry": 4.0.0-beta.101
  "@effect/platform-browser": 4.0.0-beta.101
  "@effect/platform-bun": 4.0.0-beta.101
  "@effect/platform-node": 4.0.0-beta.101
  "@effect/platform-node-shared": 4.0.0-beta.101
  "@effect/vitest": 4.0.0-beta.101
